---
title: "QP1 Visualization"
output: html_document
date: "04-0-1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(ggplot2)
library(dplyr)
library(ggthemes)
library(stringr)
data <- read.csv('../results/multi_metric_results.csv')
#data <- read.csv('../results/multi_metric_results_final.csv')
factor.cols <- c("model", "model_names", "model_state", "model_size", "language", "probe", "task", "corpus", "task_name", "metric")

num.cols <- c("score")
int.cols <- c("layer")
data[factor.cols] <- lapply(data[factor.cols], as.factor)
data[num.cols] <- lapply(data[num.cols], as.numeric)
data[int.cols] <- lapply(data[int.cols], as.integer)

layer_sizes <- c("12", "24", "0")
names(layer_sizes) <- c("Base", "Large", "Baseline")
layer_sizes['Base']

get_model_size <- function(string){
  if (string == 'Base'){
    return(12)
  }
  else if (string == 'Large'){
    return(24)
  }
  else{
    return(0)
  }
  }

data["max_layer"] <- sapply(data$model_size, get_model_size)

data['model_percent'] <- data$layer / data$max_layer

#data_target_loss <- read.csv('../results/full_results_alternative.csv')
#data_target_loss[factor.cols] <- lapply(data_target_loss[factor.cols], as.factor)
#data_target_loss[num.cols] <- lapply(data_target_loss[num.cols], as.numeric)

data
```
```{r}
data['Model'] <- data$model_names
data['State'] <- data$model_state
data['Language'] <- data$corpus
data['Comparison'] <- data$model_names
  
data <- data %>%mutate(Language = case_when(corpus %in% c('switchboard') ~ 'English', corpus %in% c('mandarin-timit') ~ 'Mandarin'))

data <- data %>% mutate(Comparison = case_when(model_names %in% c('HuBert', 'WavLM') ~ 'Other', model_names %in% c('English Large', 'English Base', 'Mandarin Base') ~ 'Monolingual wav2vec 2.0', model_names %in% c('Multiligual Large 128', 'Multilingual Large 53') ~ 'Multilingual wav2vec 2.0', model_names %in% c('English Finetuned', 'Mandarin Finetuned' ~ 'Fine-tuned'))

plot_df <- data[((data$metric == 'f1')|(data$metric == 'R2')) &(data$corpus != 'yemba')&(data$corpus != 'bu_radio')&(data$probe == 'linear')&(data$model_type != 'Baseline')&((data$task == 'tone')|(data$task == 'syllables_accents')|(data$task == 'stress')),]

plot_df %>% ggplot(aes(x=model_percent, y=score, color=language, shape=Model, linetype=State))+
  geom_line()+
  geom_point()+
  facet_grid(~ task_name, space = "free_x", scales = "free_x") +
    scale_y_continuous(limits = c(0, 1)) +
    theme(legend.position="bottom") +
    theme_base(base_size = 14) +
    theme(
      rect = element_blank(),
      panel.grid.major = element_line(colour = "grey"),
      legend.position="bottom",
      legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-5,-5,-5)
    ) 
  

```


```{r}
data['Model'] <- data$model_names
data['State'] <- data$model_state
data['Language'] <- data$language
data.tone.stress <- data[
  ((data$task == 'tone' )|(data$task == 'stress')|(data$task == 'syllables_accents'))&
    ((data$model == 'wav2vec2-base')|(data$model == 'mandarin-wav2vec2'))&(data$metric == 'f1')&(data$corpus != 'yemba')&(data$probe == 'linear'),]

data.tone.stress.baseline <- data[
  ((data$task == 'tone' )|(data$task == 'stress')|(data$task == 'syllables_accents'))&
    ((data$model == 'fbank')|(data$model == 'random'))&(data$metric == 'f1'),]

data.tone.stress %>% ggplot(aes(x=layer, y=score, color=Model, shape=Model))+
  geom_line() +
  geom_point() +
  ylim(0,1) +
  geom_hline(data=data.tone.stress.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  facet_wrap(~task_name, nrow=3)
ggsave('paper_plots/classification_comparison.png', width= 10, height=10)
```

```{r}


data.tone.accent <- data[
  ((data$task == 'tone' )|(data$task == 'syllables_accents'))&
    ((data$model == 'wav2vec2-base')|(data$model == 'mandarin-wav2vec2'))&(data$metric == 'f1')&(data$corpus != 'yemba'),]

data.tone.accent.baseline <- data[
  ((data$task == 'tone' )|(data$task == 'syllables_accents'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]


data.tone.accent %>% ggplot(aes(x=layer, y=score, color=Model, shape=Model))+
  geom_line() +
  geom_point() +
  geom_hline(data=data.tone.accent.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1) +
  facet_wrap(~task_name)
ggsave('presentation_plots/accent_comparison.png', height=20)
```

```{r}
data.f0 <- data[
  ((data$task == 'f0' ))& (data$model_size != 'Large')&(data$model_type == 'Wav2Vec2.0')&(data$metric == 'R2')&(data$corpus != 'yemba'),]

data.f0.baseline <- data[
  ((data$task == 'f0'))&
    ((data$model == 'fbank'))&(data$metric == 'R2'),]



data.f0 %>% ggplot(aes(x=layer, y=score, color=Language, shape=State))+
  geom_line() +
  geom_point(size=2) +
  geom_hline(data=data.f0.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1) +
  facet_wrap(~corpus)
ggsave('presentation_plots/f0_finetuning.png', width=15)
```

```{r}
data['State'] <- data$model_state
data.stress.finetune <- data[
  ((data$task == 'stress' )|(data$task=='tone')|(data$task == 'syllables_accents'))& (data$model_size != 'Large')&(data$model_type == 'Wav2Vec2.0')&(data$metric == 'f1')&(data$corpus != 'yemba')&(data$probe == 'linear'),]

data.stress.finetune.baseline <- data[
  ((data$task == 'tone')|(data$task=='stress'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.stress.finetune %>% ggplot(aes(x=layer, y=score, color=Language, shape=State, linetype=State))+
  geom_line() +
  geom_point(size=2) +
  geom_hline(data=data.stress.finetune.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1) +
  facet_wrap(~task_name)
ggsave('paper_plots/stress_tone_finetuning.png', width=20)
```
```{r}
data.accent.finetune <- data[
  ((data$task == 'stress' )|(data$task=='syllables_accents'))& (data$model_size != 'Large')&(data$model_type == 'Wav2Vec2.0')&(data$metric == 'f1')&(data$corpus != 'yemba'),]
data.accent.finetune$task_name <- factor(data.accent.finetune$task_name, levels=c('Lexical Stress', 'English Pitch Accent'))
data.accent.finetune.baseline <- data[
  ((data$task == 'syllables_accents')|(data$task=='stress'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.accent.finetune %>% ggplot(aes(x=layer, y=score, color=language, shape=model_names))+
  geom_line() +
  geom_point() +
  geom_hline(data=data.accent.finetune.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1) +
  facet_wrap(~task_name)
ggsave('presentation_plots/stress_accent_finetuning.png', width=15)
```


```{r}
data.large.pretrained <- data[
  ((data$task == 'syllables_accents' )|(data$task=='stress_polysyllabic')|(data$task == 'tone'))&(data$model_type == 'Wav2Vec2.0')&(data$metric == 'f1')&(data$model_state == 'Pre-trained')&(data$model != 'wav2vec2-large')&(data$corpus != 'yemba')&(data$probe == 'linear'),]

data.all.baseline <- data[
  ((data$task == 'stress_polysyllabic')|(data$task=='syllables_accents')|(data$task == 'tone'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.large.pretrained %>% ggplot(aes(x=model_percent, y=score, color=model_names, shape=model_names))+
  geom_line() +
  geom_point() +
  geom_hline(data=data.all.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  facet_wrap(~task_name)
ggsave('paper_plots/large_models.png', width=15)
```

```{r}
data.large.pretrained.scaffold <- data[
  ((data$task == 'syllables_accents' )|(data$task=='stress')|(data$task == 'tone'))&(data$model_type == 'Wav2Vec2.0')&(data$metric == 'f1')&(data$model_state == 'Pre-trained')&(data$model_size != 'Large')&(data$corpus != 'yemba')&(data$probe == 'linear'),]

data.all.baseline <- data[
  ((data$task == 'stress')|(data$task=='syllables_accents')|(data$task == 'tone'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.large.pretrained.scaffold %>% ggplot(aes(x=model_percent, y=score, color=model_names, shape=model_names))+
  geom_line() +
  geom_point() +
  geom_hline(data=data.all.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1) +
  facet_wrap(~task_name)
ggsave('presentation_plots/large_models_scaffold.png', width=15)
```

```{r}
data.mlp <- data[(data$task == 'stress')&(data$metric == 'f1')&(data$model == 'wav2vec2-base'),]

data.all.baseline <- data[
  ((data$task == 'stress'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.mlp %>% ggplot(aes(x=model_percent, y=score, color=model_names, shape=probe))+
  geom_line() +
  geom_point() +
  geom_hline(data=data.all.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1)
data.mlp
```

```{r}
data.intensity <- data[((data$task == 'intensity_parselmouth')|(data$task == 'energy'))&(data$metric == 'R2')&(data$model=='wav2vec2-base')&(data$probe != 'mlp'),]

data.intensity.baseline <- data[
  ((data$task == 'intensity_parselmouth'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.intensity %>% ggplot(aes(x=model_percent, y=score, color=task_name, shape=task_name))+
  geom_line() +
  geom_point() +
  #geom_hline(data=data.all.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  ylim(0,1)+
  facet_wrap(~corpus)
ggsave('presentation_plots/intensity_energy_comparison.png', width=15)
```

```{r}
data.all.english <- data[((data$task == 'stress')|(data$task == 'tone')|(data$task == 'syllables_accents'))&(data$metric == 'f1')&(data$language == 'English')&(data$model_size == 'Base')&(data$model_state=='Pre-trained')&(data$probe == 'linear')&(data$corpus != 'yemba'),]

data.all.baseline <- data[
  ((data$task == 'stress')|(data$task == 'tone')|(data$task == 'syllables_accents'))&
    ((data$model == 'fbank'))&(data$metric == 'f1'),]

data.all.english %>% ggplot(aes(x=model_percent, y=score, color=model_names, shape=model_names))+
  geom_line() +
  geom_point() +
  ylim(0,1)+
  geom_hline(data=data.all.baseline, aes(yintercept=score), linetype='dashed', color='red') +
  theme_bw()+
  facet_wrap(~task)
  ylim(0,1)
```

```{r}
stress.poly <- data[((data$task == 'stress_polysyllabic')|(data$task == 'stress'))&(data$metric == 'f1')&((data$model_type == 'Wav2Vec2.0')&(data$model_state == 'Pre-trained')&(data$model_size == 'Base'))&(data$probe == 'linear'),]

stress.poly %>% ggplot(aes(x=layer, y=score, color=model_names, shape=model_names))+
  geom_line()+
  geom_point() +
  ylim(0, 1) +
  facet_wrap(~task_name)
plot_df %>% ggplot(aes(x=model_percent, y=score, color=model_names, shape=rowSource, linetype=rowSource))+
  geom_line()+
  geom_point() +
  ylim(0, 1) +
  facet_wrap(~task+model)
ggsave('paper_plots/sanity_check.png', width=20, height=20)
```

```{r}
data.plot <- data[(data$metric == 'f1')|(data$metric == 'R2'),]
data %>% ggplot(aes(x = layer, y = score, group = task)) +
    geom_line(aes(linetype = Model), color = "grey", show.legend = FALSE) +
    geom_point(aes(shape =Model), size = 3) +
    geom_point(
      aes(shape = Dataset),
      size = 3.5,
      stroke = 1,
      color = "#e41a1c",
      data = plot_top_ranked,
      show.legend = FALSE
      # position = "jitter"
    ) +
    facet_grid(~ Model, space = "free_x", scales = "free_x") +
    scale_y_continuous(limits = c(0, 1)) +
    theme(legend.position="bottom") +
    theme_base(base_size = 14) +
    theme(
      rect = element_blank(),
      panel.grid.major = element_line(colour = "grey"),
      legend.position="bottom",
      legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-5,-5,-5)
    ) +
    scale_shape_manual(values = c(
      18, # eng-mav
      19, # nld-gng
      2,  # gbb-pd
      6,  # wrm-pd
      3,  # wrl-mb
      4,  # gup-wat
      8,  # pjt-sw01
      1,  # wbp-jk
      0,  # mwf-jm
      5   # gbb-lg
    )) +
    guides(
      colour = guide_legend(show = FALSE),
      shape = guide_legend(override.aes = list(size = 4), nrow = 1)
    )

```

```{r}
plot_mtwvs <- function(mtwv_df, wav2vec_checkpoint_name = "wav2vec 2.0 Large (LibriSpeech 960h)"){

  plot_df <- mtwv_df %>%
    rename(
      Model  = model,
      Layer = model_percent,
      Score     = score
    ) %>%
    mutate(
      #Model = case_when(
      #  Model %in% c("random", "fbank")    ~ str_to_upper(Model),
      #),
#      Dataset = ifelse(
#        Dataset %in% c("FBANK", "RANDOM"),
#        Dataset,
#        Dataset
#      ), #%>%
      # Legend ordering
      Model = factor(
        Model,
        levels = c("wav2vec2-base", "mandarin-wav2vec2", "mandarin-wav2vec2-aishell1", "wav2vec2-base-100h", "wav2vec2-large", "wav2vec2-xls-r-300m", "wav2vec2-large-xlsr-53", "hubert-base-ls960", "wavlm-base", 'random', 'fbank') ),
      State = factor(
        State,
        levels = c("Pre-trained", "Fine-tuned", "Baseline")
      ),
      )
  # Renaming plot_df the same name is ripe for variable name conflicts
  # But alas I am lazy and it works
  print(plot_df)
  baseline_df <- plot_df[(plot_df$Model %in% c('random', 'fbank')),]
  plot_df <- plot_df[!(plot_df$Model %in% c('random', 'fbank')),]
  
  plot_top_ranked <- plot_df %>% 
    group_by(task_name, Model) %>%
    slice_max(order_by = Score, n = 1)
  print(plot_df)
  print(baseline_df)
  plot_df %>% 
    ggplot(aes(x = Layer, y = Score, group = Model)) +
    geom_line(aes(color = Model), size=1.25, show.legend=FALSE) +
    geom_point(aes(shape = Model), size = 2) +
    geom_point(
      aes(shape = Model),
      size = 1.5,
      stroke = 1,
      color = "#e41a1c",
      data = plot_top_ranked,
      show.legend = FALSE
      # position = "jitter"
    ) +
    geom_hline(data=baseline_df, aes(yintercept=Score, color=Model), linetype='dashed', show.legend=FALSE) +
    facet_grid(~task_name,space = "free_x", scales = "free_x",) +
    scale_y_continuous(limits = c(0, 1)) +
    theme(legend.position="bottom") +
    theme_base(base_size = 14) +
    theme(
      rect = element_blank(),
      panel.grid.major = element_line(colour = "grey"),
      legend.position="bottom",
      legend.margin=margin(0,0,0,0),
      legend.box.margin=margin(-5,-5,-5,-5)
    ) +
    #ylim(0.25, 1) +
    scale_shape_manual(values = c(
      18, # eng-mav
      19, # nld-gng
      2,  # gbb-pd
      6,  # wrm-pd
      3,  # wrl-mb
      4,  # gup-wat
      8,  # pjt-sw01
      1,  # wbp-jk
      0,  # mwf-jm
      5   # gbb-lg
    )) +
    scale_x_discrete(guide = guide_axis(n.dodge=3)) +
    guides(
      colour = guide_legend(show = FALSE),
      shape = guide_legend(override.aes = list(size = 4), nrow = 2)
    )
}
```


```{r}

library(ggplot2)
library(dplyr)
library(ggthemes)
library(stringr)
data <- read.csv('../results/multi_metric_results.csv')
data2 <- read.csv('../results/multi_metric_results_final.csv')
data.cols <- names(data)
data$source <- 'first pass'
data2$source <- 'second pass'
data <- merge(x=data, y=data2, all=TRUE, by=data.cols)
data$rowSource <- apply(data[c("source.x", "source.y")], 1, 
                          function(x) paste(na.omit(x), collapse = ""))
data <- data[(data$rowSource == 'first pass')|(data$model == 'random'),]
factor.cols <- c("model", "model_names", "model_state", "model_size", "language", "probe", "task", "corpus", "task_name", "metric")

num.cols <- c("score")
int.cols <- c("layer")
data[factor.cols] <- lapply(data[factor.cols], as.factor)
data[num.cols] <- lapply(data[num.cols], as.numeric)
data[int.cols] <- lapply(data[int.cols], as.integer)

layer_sizes <- c("12", "24", "0")
names(layer_sizes) <- c("Base", "Large", "Baseline")
layer_sizes['Base']

get_model_size <- function(string){
  if (string == 'Base'){
    return(12)
  }
  else if (string == 'Large'){
    return(24)
  }
  else{
    return(1)
  }
}

#data <- data %>% mutate(layer = case_when(model_size %in% c('Large') ~ layer / 2, model_size %in% c('Base') ~ layer))

data["max_layer"] <- sapply(data$model_size, get_model_size)

data['model_percent'] <- (data$layer / data$max_layer)*12
#data['Model'] <- data$model_names
data['State'] <- data$model_state
data['Language'] <- data$corpus
data['Comparison'] <- data$model_names
data <- data %>%mutate(Language = case_when(corpus %in% c('switchboard') ~ 'English', corpus %in% c('mandarin-timit') ~ 'Mandarin'))

monolingual_models <- c('English Large', 'English Base', 'Mandarin Base', 'English Finetuned', 'Mandarin Finetuned', 'English Large Finetuned', 'English Large Finetunted', 'random')
multilingual_models <- c('Multilingual Large 128', 'Multilingual Large 53', 'random')
monolingual_base <- c('English Base', 'Mandarin Base', 'random')
monolingual_finetuned <- c('English Finetuned', 'Mandarin Finetuned', 'English Large Finetuned', 'English Large Finetunted', 'random')
other_models <- c('HuBert', 'WavLM', 'random')

data <- data %>% mutate(Comparison = case_when(model_names %in% c('HuBert', 'WavLM') ~ 'Other Models', model_names %in% monolingual_models ~ 'Monolingual wav2vec 2.0', model_names %in% multilingual_models ~ 'Multilingual wav2vec 2.0')) # model_names %in% c('English Finetuned', 'Mandarin Finetuned', 'English Large Finetuned', 'English Large Finetunted') ~ 'Fine-tuned'),)

data$task_name <- factor(data$task, levels=c("syllables_accents", "stress", "tone", "f0", "f0_300", "stress_polysyllabic", "energy", "intensity"), labels=c("Accent", "Stress", "Tone", "F0", "F0", "Stress", "RMS Energy", "Intensity (dB SPL)"),)

plot_df <- data[((data$metric == 'f1')|(data$metric == 'R2')) &!(data$model_names %in% monolingual_finetuned)&(data$corpus != 'yemba')&(data$corpus != 'bu_radio')&(data$probe == 'linear') & !(data$model %in% c('wav2vec2-large', 'wav2vec2-large-960h', 'hubert-base-ls960', 'wavlm-base', 'wav2vec2-xls-r-300m', 'wav2vec2-large-xlsr-53')) & ((data$task %in% c('stress', 'syllables_accents', 'tone')) | ((data$task == 'f0') & (data$corpus == 'switchboard'))),]

plot_df2 <- data[((data$metric == 'f1')|(data$metric == 'R2')) &(data$model_names %in% monolingual_models)&(data$corpus != 'yemba')&(data$corpus != 'bu_radio')&(data$probe == 'linear')&(data$model_type != 'Baseline')&((data$model != 'wav2vec2-large') & (data$model != 'wav2vec2-large-960h'))&((data$task == 'tone')|(data$task == 'syllables_accents')|(data$task == 'stress')|((data$task %in% c('f0', 'intensity')) & (data$corpus == 'switchboard'))),]

plot_df3 <- data[((data$metric == 'f1')|(data$metric == 'R2')) &!(data$model_names %in% monolingual_finetuned)&(data$corpus != 'yemba')&(data$corpus != 'bu_radio')&(data$probe == 'linear')&(data$model_type != 'Baseline') & (data$model %in% c('wav2vec2-base', 'mandarin-wav2vec2', 'hubert-base-ls960', 'wavlm-base')) & ((data$task %in% c('stress', 'syllables_accents', 'tone')) | ((data$task == 'f0') & (data$corpus == 'switchboard'))),]

plot_df %>% plot_mtwvs(wav2vec_checkpoint_name = "Layerwise Linear Probe Performance")
ggsave('paper_plots/all_feats_test.png', width=14)
```


